language: ruby
rvm:
- 2.1

# Cloudfront invalidation: Decrypt credentials, then run 
# https://github.com/laurilehmijoki/cf-s3-invalidator if build succeeded
before_install:
- openssl aes-256-cbc -K $encrypted_13e2bd2b9e2d_key -iv $encrypted_13e2bd2b9e2d_iv -in _cf_s3_invalidator.yml.enc -out _cf_s3_invalidator.yml -d
install: cf-s3-invalidator
after_success: cf-s3-inv

# Build and deploy the site to the S3 bucket on push to master
script: jekyll build
branches:
  only:
  - master
deploy:
  provider: s3
  access_key_id: AKIAIR4V3CAS724EMHFQ
  secret_access_key:
    secure: "DUpFkSvaCRntAEOmXO0uavWY5XELauqzniEss5OcY/lgzdRkW1gndbDf88+Qy3cfI9sA5H66z+n1pA205FJoywNAsaoo370DGwcfP7/hzerH1PvdfcebVVCPdbLCqySuMEt87xarr5k9UIV2OyNzU3CjpQlGTsiCgGejgpis3pA="
  bucket: www-rust-lang-org
  acl: public_read
  skip_cleanup: true
  local_dir: _site
  region: us-west-1
  on:
    repo: rust-lang/rust-www
    branch: master
