name: The Rust Programming Language
stable: "1.18.0"
stable_date: "2017-06-08"
stable_blog: "https://blog.rust-lang.org/2017/06/08/Rust-1.18.html"
stable_full_version: "rustc 1.18.0 (03fc9d622 2017-06-06)"
beta: "1.19"
beta_date: "2017-07-20"
nightly: "1.20"
channels:
  - name: "stable"
    vers: "1.18.0"
    package: "1.18.0"
  - name: "beta"
    vers: "1.19"
    package: "beta"
  - name: "nightly"
    vers: "1.20"
    package: "nightly"
