name: The Rust Programming Language
stable: "1.20.0"
stable_date: "2017-08-31"
stable_blog: "https://blog.rust-lang.org/2017/08/31/Rust-1.20.html"
stable_full_version: "rustc 1.20.0 (f3d6973f4 2017-08-27)"
beta: "1.21"
beta_date: "2017-10-12"
nightly: "1.22"
channels:
  - name: "stable"
    vers: "1.20.0"
    package: "1.20.0"
  - name: "beta"
    vers: "1.21"
    package: "beta"
  - name: "nightly"
    vers: "1.22"
    package: "nightly"
