name: The Rust Programming Language
stable: "1.19.0"
stable_date: "2017-07-20"
stable_blog: "https://blog.rust-lang.org/2017/07/20/Rust-1.19.html"
stable_full_version: "rustc 1.19.0 (0ade33941 2017-07-17)"
beta: "1.20"
beta_date: "2017-08-31"
nightly: "1.21"
channels:
  - name: "stable"
    vers: "1.19.0"
    package: "1.19.0"
  - name: "beta"
    vers: "1.20"
    package: "beta"
  - name: "nightly"
    vers: "1.21"
    package: "nightly"
