name: The Rust Programming Language
stable: "1.17.0"
stable_date: "2017-04-27"
stable_blog: "https://blog.rust-lang.org/2017/04/27/Rust-1.17.html"
stable_full_version: "rustc 1.17.0 (56124baa9 2017-04-24)"
beta: "1.18"
beta_date: "2017-06-08"
nightly: "1.19"
channels:
  - name: "stable"
    vers: "1.17.0"
    package: "1.17.0"
  - name: "beta"
    vers: "1.18"
    package: "beta"
  - name: "nightly"
    vers: "1.19"
    package: "nightly"
