name: The Rust Programming Language
stable: "1.16.0"
stable_date: "2017-03-16"
stable_blog: "https://blog.rust-lang.org/2017/03/16/Rust-1.16.0.html"
stable_full_version: "rustc 1.16.0 (30cf806ef 2017-03-10)"
beta: "1.17"
beta_date: "2017-04-27"
nightly: "1.18"
channels:
  - name: "stable"
    vers: "1.16.0"
    package: "1.16.0"
  - name: "beta"
    vers: "1.17"
    package: "beta"
  - name: "nightly"
    vers: "1.18"
    package: "nightly"
